version: '3'

services:
  app_veterinaria:
    build: veterinaria
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://clinica_vet:3306/veterinaria?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: ""
    restart: always
    depends_on:
      clinica_vet:
          condition: service_healthy
  clinica_vet:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: veterinaria
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10